version: "3"
services:

  maven1:
    build: ./App-1
    ports:
      - "7766:8080"
    container_name: app-1
  
  maven2:
    build: ./App-2
    ports:
       - "8866:8080"
    container_name: app-2

  nginx:
    build: ./reverse-proxy
    ports:
      - "80:80"
    container_name: reverse-proxy
